import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Icon } from "../../components/common/AppUI";
import { getApiError } from "../../services/api";
import { applyForOpportunity, getOpportunity, getSavedOpportunities, saveOpportunity, unsaveOpportunity } from "../../services/platformService";
import { Company } from "./JobCard";
import { toJobView } from "./jobUtils";
export default function JobDetailsPage() {
  const { id } = useParams(), navigate = useNavigate(); const [job, setJob] = useState(null), [saved, setSaved] = useState(false), [resume, setResume] = useState(null), [cover, setCover] = useState(""), [applying, setApplying] = useState(false), [error, setError] = useState("");
  useEffect(() => { Promise.all([getOpportunity(id), getSavedOpportunities()]).then(([row, savedRows]) => { setJob(toJobView(row)); setSaved(savedRows.some((item) => String(item.opportunity_id) === String(id))); }).catch((requestError) => setError(getApiError(requestError))); }, [id]);
  async function toggleSaved() { try { saved ? await unsaveOpportunity(id) : await saveOpportunity(id); setSaved(!saved); } catch (requestError) { setError(getApiError(requestError)); } }
  async function apply(event) { event.preventDefault(); setApplying(true); setError(""); try { await applyForOpportunity(id, cover, resume); navigate("/job-seeker/applications"); } catch (requestError) { setError(getApiError(requestError)); } finally { setApplying(false); } }
  if (!job) return <div className="panel">{error || "Loading opportunity..."}</div>;
  return <><div className="breadcrumb"><Link to="/job-seeker/jobs">Opportunities</Link><Icon name="arrow" size={13}/>{job.title}</div>{error && <div className="form-error">{error}</div>}<section className="panel job-hero"><Company name={job.company}/><div><span className="verified-line">{job.company}<em>Approved employer</em></span><h1>{job.title}</h1><p>{job.location} · {job.mode} · {job.type}</p></div><div><button className="button light" onClick={toggleSaved}>{saved ? "Saved" : "Save"}</button></div></section><div className="detail-grid"><section className="panel content"><h2>About this opportunity</h2><p>{job.description}</p><h3>Requirements</h3><p>{job.requirements || "See the opportunity description."}</p><h3>Qualification</h3><p>{job.qualification || "Not specified"}</p><h3>Closing date</h3><p>{job.closing}</p></section><aside className="panel match-panel"><h2>Apply now</h2><form onSubmit={apply}><label>Short cover letter<textarea rows="6" value={cover} onChange={(event) => setCover(event.target.value)} maxLength="5000"/></label><div className="saved-cv-note"><Icon name="check"/><span><b>Your saved profile CV will be used</b><small>You can select another PDF below if needed.</small></span></div><label>Use a different CV (optional)<input type="file" accept="application/pdf,.pdf" onChange={(event) => setResume(event.target.files?.[0] || null)}/></label>{resume && <small className="cv-selected">Selected: {resume.name}</small>}<button className="button primary" disabled={applying}>{applying ? "Submitting..." : "Submit application"}</button></form></aside></div></>;
}
