import { useState } from "react";
import { Icon, Intro } from "../../components/common/AppUI";
import useLocalStorage from "../../hooks/useLocalStorage";

const initialProfile={fullName:"Naledi Mthembu",email:"naledi@example.co.za",phone:"071 234 5678",city:"Richards Bay",province:"KwaZulu-Natal",qualification:"BSc Computer Science",institution:"University of Zululand",studyStatus:"Final year",graduationYear:"2026",summary:"Final-year Computer Science student interested in software development and data analysis.",preferredRoles:"Graduate Software Developer, Junior Data Analyst",workMode:"Hybrid",availability:"Immediately",skills:["Python","JavaScript","SQL"],projects:["Graduate opportunity finder built with React."],cv:"Naledi_Mthembu_CV.pdf"};

export default function JobSeekerProfilePage() {
  const [profile,setProfile]=useLocalStorage("graduatelink-seeker-profile",initialProfile);
  const [draft,setDraft]=useState(profile),[saved,setSaved]=useState(false),[newSkill,setNewSkill]=useState("");
  const change=(field,value) => {setSaved(false);setDraft((current) => ({...current,[field]:value}));};
  const save=() => {setProfile(draft);setSaved(true)};
  const addSkill=() => {const skill=newSkill.trim();if(skill&&!draft.skills.includes(skill)){change("skills",[...draft.skills,skill]);setNewSkill("")}};

  return <><Intro eyebrow="CAREER PROFILE" title="Your complete career profile" copy="Employers use this information when reviewing your applications." action={<button className="button primary small" onClick={save}>{saved?"Profile saved":"Save profile"}</button>}/>{saved&&<div className="success"><Icon name="check"/>Your profile changes were saved.</div>}<section className="panel long-form">
    <h2 className="form-title">Personal information</h2><div className="form-grid"><Field label="Full name" value={draft.fullName} onChange={(value) => change("fullName",value)}/><Field label="Email address" type="email" value={draft.email} onChange={(value) => change("email",value)}/><Field label="Phone number" value={draft.phone} onChange={(value) => change("phone",value)}/><Field label="City" value={draft.city} onChange={(value) => change("city",value)}/><Field label="Province" value={draft.province} onChange={(value) => change("province",value)}/><label>Availability<select value={draft.availability} onChange={(event) => change("availability",event.target.value)}><option>Immediately</option><option>After graduation</option><option>One month notice</option></select></label><label className="wide">Professional summary<textarea rows="4" value={draft.summary} onChange={(event) => change("summary",event.target.value)}/></label></div>
    <h2 className="form-title">Education</h2><div className="form-grid"><Field label="Qualification" value={draft.qualification} onChange={(value) => change("qualification",value)}/><Field label="Institution" value={draft.institution} onChange={(value) => change("institution",value)}/><label>Study status<select value={draft.studyStatus} onChange={(event) => change("studyStatus",event.target.value)}><option>Final year</option><option>Graduated</option><option>Postgraduate</option></select></label><Field label="Graduation year" type="number" value={draft.graduationYear} onChange={(value) => change("graduationYear",value)}/></div>
    <h2 className="form-title">Career preferences</h2><div className="form-grid"><Field label="Preferred roles" value={draft.preferredRoles} onChange={(value) => change("preferredRoles",value)}/><label>Preferred work mode<select value={draft.workMode} onChange={(event) => change("workMode",event.target.value)}><option>Hybrid</option><option>Remote</option><option>On-site</option><option>Any</option></select></label></div>
    <h2 className="form-title">Skills</h2><div className="tag-editor">{draft.skills.map((skill) => <span key={skill}>{skill}<button type="button" onClick={() => change("skills",draft.skills.filter((item) => item!==skill))}>×</button></span>)}</div><div className="inline-add"><input value={newSkill} onChange={(event) => setNewSkill(event.target.value)} placeholder="Add a skill"/><button type="button" className="button light small" onClick={addSkill}><Icon name="plus"/>Add skill</button></div>
    <h2 className="form-title">Projects and experience</h2><label>One project or experience per line<textarea rows="5" value={draft.projects.join("\n")} onChange={(event) => change("projects",event.target.value.split("\n"))}/></label>
    <h2 className="form-title">Curriculum Vitae</h2><div className="item-row"><Icon name="doc"/><span><b>{draft.cv||"No CV uploaded"}</b><small>PDF used when applying</small></span><label className="file-action">Replace CV<input type="file" accept=".pdf" onChange={(event) => event.target.files[0]&&change("cv",event.target.files[0].name)}/></label></div>
  </section></>;
}

function Field({label,type="text",value,onChange}) { return <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
