import { useState } from "react";
import { Link } from "react-router-dom";
import { Icon, Intro, Stat, Status } from "../../components/common/AppUI";

export function EmployerDashboard({ opportunities }) {
  return <><Intro eyebrow="EMPLOYER DASHBOARD" title="Good afternoon, Thandi" copy="Manage your organisation, opportunities and applicants." action={<Link className="button primary small" to="/employer/opportunities/new"><Icon name="plus"/>Post opportunity</Link>}/><div className="verification"><Icon name="shield"/><span><b>Organisation approved</b><p>Your organisation was reviewed by an Administrator.</p></span><em>Approved</em></div><div className="stats"><Stat label="Active opportunities" value={opportunities.filter(item=>item.status==="Active").length} note="Published listings" icon="briefcase"/><Stat label="Total applicants" value={opportunities.reduce((sum,item)=>sum+item.applicants,0)} note="Across your listings" tone="teal" icon="user"/><Stat label="Verification" value="Approved" note="Publishing allowed" tone="purple" icon="shield"/></div><section className="panel"><h2 className="form-title">Recent opportunities</h2><OpportunityTable opportunities={opportunities}/></section></>;
}

export function EmployerOpportunitiesPage({ opportunities, setOpportunities }) {
  function edit(item) { const title=prompt("Update opportunity title",item.title); if(title)setOpportunities(list=>list.map(row=>row.id===item.id?{...row,title}:row)); }
  function close(item) { setOpportunities(list=>list.map(row=>row.id===item.id?{...row,status:"Closed"}:row)); }
  return <><Intro eyebrow="MY OPPORTUNITIES" title="Manage your opportunities" copy="Edit or close opportunities belonging to your organisation." action={<Link className="button primary small" to="/employer/opportunities/new">Post opportunity</Link>}/><section className="panel"><OpportunityTable opportunities={opportunities} actions={{edit,close}}/></section></>;
}

export function NewOpportunityPage({ setOpportunities }) {
  const [submitted,setSubmitted]=useState(false);
  function submit(event) { event.preventDefault(); const form=new FormData(event.currentTarget); setOpportunities(list=>[{id:Date.now(),title:form.get("title"),location:form.get("location"),applicants:0,status:"Pending",closing:form.get("closing")},...list]); setSubmitted(true); event.currentTarget.reset(); }
  return <><Intro eyebrow="NEW OPPORTUNITY" title="Create an early-career opportunity" copy="The Administrator will review it before publication."/><form className="panel long-form" onSubmit={submit}>{submitted&&<div className="success"><Icon name="check"/>Opportunity submitted for approval.</div>}<div className="form-grid"><label className="wide">Opportunity title<input name="title" required placeholder="Graduate Software Developer"/></label><label>Type<select><option>Graduate programme</option><option>Internship</option><option>Learnership</option><option>Entry-level job</option></select></label><label>Work arrangement<select><option>Hybrid</option><option>Remote</option><option>On-site</option></select></label><label>Location<input name="location" required/></label><label>Closing date<input name="closing" type="date" required/></label><label className="wide">Qualification<input required/></label><label className="wide">Required skills<input placeholder="React, SQL, Git" required/></label><label className="wide">Description<textarea rows="5" required/></label></div><div className="form-actions"><button className="button primary">Submit for approval</button></div></form></>;
}

export function ApplicantsPage() {
  const [applicants,setApplicants]=useState([{id:1,name:"Lwazi Khumalo",qualification:"BSc Information Technology",match:"88%",status:"Shortlisted"},{id:2,name:"Ayanda Cele",qualification:"Diploma in ICT",match:"84%",status:"Under review"},{id:3,name:"Sipho Dlamini",qualification:"BSc Computer Science",match:"80%",status:"Applied"}]),[selected,setSelected]=useState(null);
  return <><Intro eyebrow="APPLICANTS" title="Review submitted applications" copy="You can only view applicants for your own opportunities."/>{selected&&<div className="success"><Icon name="user"/><span><b>{selected.name}</b> · {selected.qualification} · CV and skills available.</span><button onClick={()=>setSelected(null)}>Close</button></div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Qualification</th><th>Match</th><th>Status</th><th>Profile</th></tr></thead><tbody>{applicants.map(applicant=><tr key={applicant.id}><td><b>{applicant.name}</b></td><td>{applicant.qualification}</td><td>{applicant.match}</td><td><select className="status-select" value={applicant.status} onChange={e=>setApplicants(list=>list.map(row=>row.id===applicant.id?{...row,status:e.target.value}:row))}>{["Applied","Under review","Shortlisted","Interview","Accepted","Rejected"].map(status=><option key={status}>{status}</option>)}</select></td><td><button className="text-action" onClick={()=>setSelected(applicant)}>Review</button></td></tr>)}</tbody></table></div></section></>;
}

export function OrganisationProfilePage() {
  const [document,setDocument]=useState("No document selected"),[status,setStatus]=useState("Not submitted"),[saved,setSaved]=useState(false);
  return <><Intro eyebrow="ORGANISATION PROFILE" title="Company details and verification" copy="Complete the profile and submit proof for Administrator review." action={<button className="button primary small" onClick={()=>setSaved(true)}>{saved?"Profile saved":"Save profile"}</button>}/><div className="verification"><Icon name="shield"/><span><b>Verification: {status}</b><p>Only approved organisations can publish opportunities.</p></span><Status>{status}</Status></div><section className="panel long-form"><div className="form-grid"><label>Organisation name<input defaultValue="Thrive Digital"/></label><label>Registration number<input defaultValue="2024/123456/07"/></label><label>Email<input defaultValue="careers@thrivedigital.co.za"/></label><label>Website<input defaultValue="https://thrivedigital.co.za"/></label><label className="wide">Description<textarea rows="4" defaultValue="Technology company supporting graduate development."/></label></div><h2 className="form-title">Verification document</h2><div className="item-row"><Icon name="doc"/><span><b>{document}</b><small>Company registration certificate or approved proof</small></span><label className="file-action">Choose file<input type="file" accept=".pdf,.png,.jpg" onChange={e=>e.target.files[0]&&setDocument(e.target.files[0].name)}/></label></div><div className="form-actions"><button className="button primary" disabled={document==="No document selected"} onClick={()=>setStatus("Pending")}>Submit verification</button></div></section></>;
}

function OpportunityTable({ opportunities, actions }) {
  return <div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Applicants</th><th>Closing</th><th>Status</th>{actions&&<th>Actions</th>}</tr></thead><tbody>{opportunities.map(item=><tr key={item.id}><td><b>{item.title}</b><span>{item.location}</span></td><td>{item.applicants}</td><td>{item.closing}</td><td><Status>{item.status}</Status></td>{actions&&<td><div className="row-actions"><button onClick={()=>actions.edit(item)}>Edit</button><button disabled={item.status==="Closed"} onClick={()=>actions.close(item)}>Close</button></div></td>}</tr>)}</tbody></table></div>;
}
