import { useState } from "react";
import { Icon, Intro, Status } from "../../components/common/AppUI";
import useLocalStorage from "../../hooks/useLocalStorage";

const initialProfile={contactName:"Thandi Dlamini",organisationName:"Thrive Digital",registrationNumber:"2024/123456/07",email:"careers@thrivedigital.co.za",phone:"031 555 0102",website:"https://thrivedigital.co.za",industry:"Information Technology",city:"Durban",province:"KwaZulu-Natal",size:"11–50 employees",description:"Technology company supporting graduate development.",document:"",status:"Not submitted"};

export default function OrganisationProfilePage() {
  const [profile,setProfile]=useLocalStorage("graduatelink-employer-profile",initialProfile);
  const [draft,setDraft]=useState(profile),[saved,setSaved]=useState(false);
  const change=(field,value) => {setSaved(false);setDraft((current) => ({...current,[field]:value}));};
  const save=() => {setProfile(draft);setSaved(true)};
  const submitVerification=() => {const updated={...draft,status:"Pending"};setDraft(updated);setProfile(updated)};
  return <><Intro eyebrow="ORGANISATION PROFILE" title="Company details and verification" copy="Employers must provide complete information before publishing opportunities." action={<button className="button primary small" onClick={save}>{saved?"Profile saved":"Save profile"}</button>}/>{saved&&<div className="success"><Icon name="check"/>Organisation profile saved.</div>}<div className="verification"><Icon name="shield"/><span><b>Verification: {draft.status}</b><p>Only approved organisations can publish opportunities.</p></span><Status>{draft.status}</Status></div><section className="panel long-form"><h2 className="form-title">Organisation information</h2><div className="form-grid"><Field label="Contact person" value={draft.contactName} onChange={(value) => change("contactName",value)}/><Field label="Organisation name" value={draft.organisationName} onChange={(value) => change("organisationName",value)}/><Field label="Registration number" value={draft.registrationNumber} onChange={(value) => change("registrationNumber",value)}/><Field label="Email address" type="email" value={draft.email} onChange={(value) => change("email",value)}/><Field label="Phone number" value={draft.phone} onChange={(value) => change("phone",value)}/><Field label="Website" type="url" value={draft.website} onChange={(value) => change("website",value)}/><Field label="Industry" value={draft.industry} onChange={(value) => change("industry",value)}/><Field label="Company size" value={draft.size} onChange={(value) => change("size",value)}/><Field label="City" value={draft.city} onChange={(value) => change("city",value)}/><Field label="Province" value={draft.province} onChange={(value) => change("province",value)}/><label className="wide">Organisation description<textarea rows="5" value={draft.description} onChange={(event) => change("description",event.target.value)}/></label></div><h2 className="form-title">Verification document</h2><div className="item-row"><Icon name="doc"/><span><b>{draft.document||"No document selected"}</b><small>Company registration certificate or approved proof</small></span><label className="file-action">Choose file<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={(event) => event.target.files[0]&&change("document",event.target.files[0].name)}/></label></div><div className="form-actions"><button className="button primary" disabled={!draft.document} onClick={submitVerification}>Submit verification</button></div></section></>;
}

function Field({label,type="text",value,onChange}) { return <label>{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
