"""Role-aware GradBot. Every /chat reply is generated by the trained adapter."""
import logging
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from ..database import get_database
from ..dependencies import bearer_scheme, require_roles
from ..models import User, JobSeekerProfile
from ..security import decode_access_token
from ..services.gradbot_model import answer as model_answer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/gradbot", tags=["GradBot"])

class ChatRequest(BaseModel):
    message: str = Field(min_length=2, max_length=2000)

class ChatResponse(BaseModel):
    answer: str
    links: list[str] = []
    suggested_questions: list[str] = []


def optional_user(credentials: HTTPAuthorizationCredentials | None, database: Session) -> User | None:
    if credentials is None:
        return None
    try:
        payload = decode_access_token(credentials.credentials)
        user = database.get(User, int(payload["sub"]))
    except Exception as error:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid authentication token") from error
    if user is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User account not found")
    if not user.is_active:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Account suspended")
    return user

@router.post("/chat", response_model=ChatResponse)
def chat(data: ChatRequest, credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
         database: Session = Depends(get_database)):
    user = optional_user(credentials, database)
    role = user.role if user else "visitor"
    try:
        answer = model_answer(data.message, role)
        if not answer:
            raise RuntimeError('GradBot returned empty output')
    except Exception:
        logger.exception('GradBot model inference failed')
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                            detail="GradBot model is unavailable")
    return ChatResponse(answer=answer)

class CVDraft(BaseModel):
    """Editable draft; nothing is saved to the database or existing uploaded CV."""
    text: str
    missing_fields: list[str]


def build_cv_draft(user: User, profile: JobSeekerProfile | None) -> CVDraft:
    name = " ".join(x for x in (user.first_name, user.last_name) if x).strip()
    if not name and profile:
        name = (profile.full_name or "").strip()
    missing = []
    if not name:
        missing.append("name")
    if not profile or not profile.phone:
        missing.append("phone")
    if not profile or not profile.professional_summary:
        missing.append("professional summary")
    if not profile or not profile.qualification:
        missing.append("qualification")
    if not profile or not profile.institution:
        missing.append("institution")
    if not profile or not profile.skills:
        missing.append("skills")
    parts = [name or "[Your full name]", user.email]
    if profile:
        contact = [v for v in (profile.phone, profile.city, profile.province) if v]
        if contact:
            parts.append(" | ".join(contact))
        if profile.professional_summary:
            parts += ["", "PROFESSIONAL SUMMARY", profile.professional_summary.strip()]
        education = [v for v in (profile.qualification, profile.institution,
                                 profile.study_status, profile.graduation_year) if v and v != "0"]
        if education:
            parts += ["", "EDUCATION", " | ".join(education)]
        if profile.skills:
            parts += ["", "SKILLS", ", ".join(str(v) for v in profile.skills if v)]
        if profile.projects:
            parts += ["", "PROJECTS AND EXPERIENCE"]
            parts += ["- " + str(v) for v in profile.projects if v]
    return CVDraft(text="\n".join(parts).strip() + "\n", missing_fields=missing)


@router.get("/me/cv-draft", response_model=CVDraft)
def my_cv_draft(current_user: User = Depends(require_roles("job_seeker")),
                database: Session = Depends(get_database)):
    return build_cv_draft(current_user, database.get(JobSeekerProfile, current_user.id))
